import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'it' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation object
const translations = {
  it: {
    // Header
    'header.searchPlaceholder': 'Cerca negozi, categorie...',
    'header.favorites': 'Preferiti',
    'header.profile': 'Profilo',
    'header.hello': 'Ciao',
    'header.logout': 'Esci',
    'header.login': 'Accedi',
    'header.tagline': 'Local-Eyes',
    
    // Hero section
    'hero.title': 'Vedi locale, Vivi locale',
    'hero.subtitle': 'Gli occhi della tua comunità digitale. Scopri, sostieni e condividi le gift card dei commercianti del tuo quartiere. Insieme facciamo fiorire l\'economia locale.',
    'hero.stats.merchants': 'Commercianti Locali',
    'hero.stats.giftCards': 'Gift Card Attivate', 
    'hero.stats.neighborhoods': 'Quartieri Connessi',
    
    // Mission Banner
    'mission.title': 'La nostra missione',
    'mission.quote': 'Riportiamo lo sguardo al locale. Ogni gift card è un investimento nel futuro del tuo quartiere.',
    'mission.button': 'Unisciti al movimento',
    
    // Common
    'common.loading': 'Caricamento...',
    'common.error': 'Errore',
    'common.save': 'Salva',
    'common.cancel': 'Annulla',
    'common.close': 'Chiudi',
    'common.delete': 'Elimina',
    'common.edit': 'Modifica',
    'common.view': 'Visualizza',
    'common.all': 'Tutti',
    'common.or': 'oppure',
    
    // Shop listing
    'shops.featuredTitle': 'I volti del tuo quartiere',
    'shops.featuredDescription': 'Ogni acquisto è uno sguardo di fiducia. Conosci le storie dei commercianti che rendono unico il tuo quartiere.',
    'shops.shopsFound': 'negozi trovati',
    'shops.loadMore': 'Carica altri negozi',
    'shops.noResults': 'Nessun negozio trovato con i filtri selezionati',
    'shops.clearFilters': 'Cancella filtri',
    'shops.unableToLoad': 'Impossibile caricare i negozi',
    'shops.discoverGiftCards': 'Scopri Gift Card',
    'shops.giftCards': 'gift card',
    
    // View toggle
    'view.list': 'Lista',
    'view.map': 'Mappa',
    
    // CTA Section
    'cta.title': 'Hai un negozio?',
    'cta.description': 'Unisciti a Localize e inizia a vendere le tue gift card online. È semplice, veloce e gratuito.',
    'cta.registerShop': 'Registra il tuo negozio',
    
    // Gift cards
    'giftCard.useNow': 'Usa ora',
    'giftCard.expired': 'Scaduta',
    'giftCard.active': 'Attiva',
    'giftCard.qrCodeTitle': 'QR Code Gift Card',
    'giftCard.showToMerchant': 'Mostra questo QR code al commerciante per utilizzare la tua gift card',
    'giftCard.code': 'Codice',
    'giftCard.details': 'Dettagli',
    'giftCard.value': 'Valore',
    'giftCard.remaining': 'Rimangono',
    'giftCard.expiresOn': 'Scade il',
    'giftCard.message': 'Messaggio',
    'giftCard.purchasedOn': 'Acquistata il',
    'giftCard.status.active': 'Attiva',
    'giftCard.status.used': 'Utilizzata',
    'giftCard.status.expired': 'Scaduta',
    'giftCard.status.cancelled': 'Annullata',
    'giftCard.status.estinta': 'Estinta',
    'giftCard.status.scaduta': 'Scaduta',
    'giftCard.status.inactive': 'Inattiva',
    
    // Profile
    'profile.title': 'Il mio profilo',
    'profile.giftCards': 'Le mie Gift Card',
    'profile.activeGiftCards': 'Gift Card Attive',
    'profile.inactiveGiftCards': 'Gift Card Disattive',
    'profile.quickActions': 'Azioni rapide',
    'profile.favoriteShops': 'Negozi preferiti',
    'profile.settings': 'Impostazioni',
    'profile.myLocations': 'Le mie posizioni',
    'profile.visit': 'Visita',
    'profile.noGiftCards': 'Non hai ancora acquistato nessuna gift card',
    'profile.exploreShops': 'Esplora negozi',
    'profile.loadingGiftCards': 'Caricamento gift card...',
    'profile.accessRequired': 'Accesso richiesto',
    'profile.loginToAccess': 'Effettua il login per accedere al tuo profilo',
    'profile.login': 'Accedi',
    'profile.backToHome': 'Torna alla Home',
    'profile.merchantDashboard': 'Dashboard Merchant',
    'profile.merchantDescription': 'Accedi alla tua dashboard per gestire le gift card e monitorare le vendite',
    'profile.goToDashboard': 'Vai alla Dashboard',
    
    // Login Select
    'loginSelect.title': 'Scegli il tipo di accesso',
    'loginSelect.description': 'Seleziona come vuoi accedere a Localize',
    'loginSelect.customer': 'Cliente',
    'loginSelect.customerDescription': 'Accedi per acquistare gift card e scoprire i negozi del tuo quartiere',
    'loginSelect.loginAsCustomer': 'Accedi come Cliente',
    'loginSelect.merchant': 'Merchant',
    'loginSelect.merchantDescription': 'Gestisci il tuo negozio, le gift card e monitora le vendite',
    'loginSelect.loginAsMerchant': 'Accedi come Merchant',
    
    // Login
    'login.title': 'Localize',
    'login.description': 'Accedi o registrati per gestire le tue gift card',
    'login.tab.login': 'Accedi',
    'login.tab.signup': 'Registrati',
    'login.email': 'Email',
    'login.emailPlaceholder': 'la-tua-email@esempio.com',
    'login.password': 'Password',
    'login.passwordPlaceholder': '••••••••',
    'login.confirmPassword': 'Conferma Password',
    'login.fullName': 'Nome completo',
    'login.namePlaceholder': 'Il tuo nome',
    'login.rememberMe': 'Ricordami',
    'login.loginButton': 'Accedi',
    'login.signupButton': 'Registrati',
    'login.loggingIn': 'Accesso in corso...',
    'login.signingUp': 'Registrazione in corso...',
    'login.continueWithGoogle': 'Continua con Google',
    'login.loginSuccess': 'Login effettuato',
    'login.welcomeMessage': 'Benvenuto in Localize!',
    'login.loginError': 'Errore di login',
    'login.invalidCredentials': 'Email o password non corretti',
    'login.signupSuccess': 'Registrazione completata',
    'login.signupWelcome': 'Benvenuto in Localize! Effettua il login per continuare.',
    'login.signupError': 'Errore di registrazione',
    'login.signupGenericError': 'Si è verificato un errore durante la registrazione',
    'login.passwordMismatch': 'Le password non coincidono',
    
    // 404
    'notFound.title': '404',
    'notFound.description': 'Oops! Pagina non trovata',
    'notFound.returnHome': 'Torna alla Home',
    
    // Shop Detail
    'shop.notFound': 'Negozio non trovato',
    'shop.description': 'Descrizione',
    'shop.contactInfo': 'Informazioni di contatto',
    'shop.openingHours': 'Orari di apertura',
    'shop.schedule': 'Lun-Sab: 09:00 - 19:00',
    'shop.phone': 'Telefono',
    'backToCatalog': 'Torna al catalogo',
    'backToHome': 'Torna alla Home',
    'reviews': 'recensioni',
    'giftCard.available': 'Gift Card Disponibili',
    'giftCard.buy': 'Acquista Gift Card',
    'giftCard.selectAmount': 'Seleziona un importo',
    'giftCard.securePayment': 'Pagamento sicuro',
    'giftCard.instantDelivery': 'Consegna immediata',
    
    // Categories
    'categories.all': 'Tutti',
    'categories.bar': 'Bar & Caffè',
    'categories.restaurant': 'Ristoranti',
    'categories.bookstore': 'Librerie',
    'categories.beauty': 'Bellezza',
    'categories.clothing': 'Abbigliamento',
    
    // Profile dropdown
    'profile.greeting': 'Ciao',
    'profile.dashboard': 'Dashboard',
    'profile.logout': 'Esci',
    'profile.defaultUser': 'utente',
    
    // Shop cards
    'shop.sampleDescription': 'Scopri questo fantastico negozio locale che offre prodotti e servizi di qualità nel cuore del quartiere.',
    'merchant.verified': 'Commerciante Verificato',
    
    // Filters
    'filters.title': 'Filtri',
    'filters.shopsTitle': 'Filtri Negozi', 
    'filters.clearAll': 'Cancella tutto',
    'filters.category': 'Categoria',
    'filters.priceRange': 'Range Prezzo Gift Card',
    'filters.minRating': 'Valutazione minima',
    'filters.allRatings': 'Tutte',
    'filters.maxDistance': 'Distanza massima',
    'filters.allDistances': 'Tutte',

    // Dashboard translations
    'allShops': 'Tutti i negozi',
    'selectedShop': 'Negozio selezionato',
    'details': 'Dettagli',
    'active': 'Attiva',
    'used': 'Utilizzata',
    'expired': 'Scaduta',
    'cancelled': 'Annullata',

    // Merchant translations
    'merchant.login.title': 'Area Merchant',
    'merchant.login.description': 'Accedi o registrati per gestire le gift card',
    'merchant.login.backHome': 'Torna alla home',
    'merchant.login.shopName': 'Nome negozio',
    'merchant.login.shopNamePlaceholder': 'Nome del tuo negozio',
    'merchant.login.confirmPassword': 'Conferma Password',
    'merchant.login.registerButton': 'Registrati come Merchant',
    'merchant.login.customerAccountConnected': 'Account cliente già connesso',
    'merchant.login.mustLogoutCustomer': 'Devi disconnetterti dall\'account cliente per accedere come merchant.',
    'merchant.login.disconnect': 'Disconnetti',
    'merchant.login.disconnected': 'Disconnesso',
    'merchant.login.canLoginMerchant': 'Ora puoi accedere come merchant.',
    'merchant.login.loggingIn': 'Accesso in corso...',
    'merchant.login.registrationInProgress': 'Registrazione in corso...',
    'merchant.login.registrationComplete': 'Registrazione completata',
    'merchant.login.registrationWelcome': 'Benvenuto! Effettua il login per accedere alla dashboard.',
    'merchant.login.registrationError': 'Errore di registrazione',
    'merchant.login.customerLogin': 'Sei un cliente?',
    'merchant.login.loginAsCustomer': 'Accedi come cliente',

    'merchant.shops.title': 'I tuoi negozi',
    'merchant.shops.description': 'Gestisci le informazioni e le configurazioni dei tuoi negozi',
    'merchant.shops.addShop': 'Aggiungi negozio',
    'merchant.shops.backToDashboard': 'Torna alla Dashboard',
    'merchant.shops.modify': 'Modifica',
    'merchant.shops.loadingError': 'Errore nel caricamento dei negozi',
    'merchant.shops.retry': 'Riprova',
    'merchant.shops.noShops': 'Nessun negozio registrato',
    'merchant.shops.registerFirst': 'Inizia registrando il tuo primo negozio per vendere gift card online',
    'merchant.shops.registerFirstShop': 'Registra il primo negozio',
    'merchant.shops.shopUpdated': 'Negozio aggiornato',
    'merchant.shops.updatedSuccess': 'Le modifiche sono state salvate con successo.',
    'merchant.shops.featureComingSoon': 'Funzionalità in arrivo',
    'merchant.shops.advancedSettings': 'Le configurazioni avanzate saranno disponibili presto.',
    'merchant.shops.statusActive': 'Attivo',
    'merchant.shops.statusInactive': 'Inattivo',
    'merchant.shops.statusPending': 'In revisione',

    'merchant.settings.title': 'Impostazioni',
    'merchant.settings.merchantSettings': 'Impostazioni Merchant',
    'merchant.settings.manageShop': 'Gestisci le impostazioni del tuo negozio e delle gift card',
    'merchant.settings.shop': 'Negozio',
    'merchant.settings.giftCards': 'Gift Card',
    'merchant.settings.notifications': 'Notifiche',
    'merchant.settings.security': 'Sicurezza',
    'merchant.settings.shopInfo': 'Informazioni Negozio',
    'merchant.settings.shopName': 'Nome Negozio',
    'merchant.settings.phone': 'Telefono',
    'merchant.settings.description': 'Descrizione',
    'merchant.settings.address': 'Indirizzo',
    'merchant.settings.website': 'Sito Web',
    'merchant.settings.openingHours': 'Orari di Apertura',
    'merchant.settings.giftCardConfig': 'Configurazione Gift Card',
    'merchant.settings.minAmount': 'Importo Minimo (€)',
    'merchant.settings.maxAmount': 'Importo Massimo (€)',
    'merchant.settings.defaultValidity': 'Validità Default (mesi)',
    'merchant.settings.defaultAmounts': 'Importi Predefiniti (€)',
    'merchant.settings.customDesign': 'Design Personalizzato',
    'merchant.settings.customDesignDesc': 'Abilita design personalizzato per le gift card',
    'merchant.settings.notificationPrefs': 'Preferenze Notifiche',
    'merchant.settings.emailOrders': 'Notifiche Ordini Email',
    'merchant.settings.emailOrdersDesc': 'Ricevi email per ogni nuovo ordine',
    'merchant.settings.emailRedemptions': 'Notifiche Utilizzo Email',
    'merchant.settings.emailRedemptionsDesc': 'Ricevi email quando una gift card viene utilizzata',
    'merchant.settings.smsNotifications': 'Notifiche SMS',
    'merchant.settings.smsDesc': 'Ricevi SMS per eventi importanti',
    'merchant.settings.weeklyReports': 'Report Settimanali',
    'merchant.settings.weeklyReportsDesc': 'Ricevi report delle vendite ogni settimana',
    'merchant.settings.monthlyReports': 'Report Mensili',
    'merchant.settings.monthlyReportsDesc': 'Ricevi report dettagliati ogni mese',
    'merchant.settings.securitySettings': 'Impostazioni Sicurezza',
    'merchant.settings.twoFactorAuth': 'Autenticazione a Due Fattori',
    'merchant.settings.twoFactorDesc': 'Aggiungi un livello extra di sicurezza al tuo account',
    'merchant.settings.sessionTimeout': 'Timeout Sessione (minuti)',
    'merchant.settings.passwordExpiry': 'Scadenza Password (giorni)',
    'merchant.settings.changePassword': 'Cambia Password',
    'merchant.settings.cancel': 'Annulla',
    'merchant.settings.save': 'Salva Impostazioni',
    'merchant.settings.saving': 'Salvataggio...',
    'merchant.settings.saved': 'Impostazioni Salvate',
    'merchant.settings.savedDesc': 'Le tue impostazioni sono state aggiornate con successo',
    'merchant.settings.error': 'Errore',
    'merchant.settings.errorDesc': 'Errore durante il salvataggio delle impostazioni',
    
    // Merchant Dashboard - Italian translations
    'merchant.dashboard': 'Dashboard Merchant',
    'merchant.selectShop': 'Seleziona negozio',
    'merchant.allShops': 'Tutti i negozi',
    'merchant.manageShops': 'Gestisci Negozi',
    'merchant.logout': 'Esci',
    'merchant.loading': 'Caricamento...',
    'merchant.authenticationInProgress': 'Verifica dell\'autenticazione in corso',
    'merchant.selectedShop': 'Negozio Selezionato',
    'merchant.totalSales': 'Vendite Totali',
    'merchant.giftCardsSold': 'Gift Card Vendute',
    'merchant.pendingRedemptions': 'Da Utilizzare',
    'merchant.totalCustomers': 'Clienti Totali',
    'merchant.pendingGiftCards': 'Gift card in attesa',
    'merchant.newCustomers': 'nuovi clienti',
    'merchant.vsLastMonth': 'vs mese scorso',
    'merchant.orders': 'Ordini',
    'merchant.giftCards': 'Gift Card',
    'merchant.analytics': 'Analytics',
    'merchant.recentOrders': 'Ordini Recenti',
    'merchant.export': 'Esporta',
    'merchant.noOrdersFound': 'Nessun ordine trovato',
    'merchant.tryChangeShop': 'Prova a cambiare negozio o visualizzare tutti i negozi',
    'merchant.activeGiftCards': 'Gift Card Attive',
    'merchant.noActiveGiftCards': 'Nessuna gift card attiva',
    'merchant.usedGiftCards': 'Gift Card Esaurite',
    'merchant.noUsedGiftCards': 'Nessuna gift card esaurita',
    'merchant.for': 'Per:',
    'merchant.salesTrend': 'Trend Vendite',
    'merchant.salesByMonth': 'Vendite per Mese',
    'merchant.giftCardSales': 'Vendite Gift Card',
    'merchant.giftCardsSoldByMonth': 'Gift Card Vendute per Mese',
    'merchant.noData': 'Nessun dato disponibile',
    'merchant.sales': 'Vendite',
    'merchant.giftCardsSoldCount': 'Gift Card Vendute',
    
    // Additional translations - Italian
    'giftCardStats': 'Statistiche Gift Card',
    'remainingValue': 'Valore residuo',
    'usedValue': 'Valore utilizzato',
    'totalGiftCards': 'Totale Gift Card',
    'totalValue': 'Valore totale',
    'noSalesLastMonths': 'Nessuna vendita negli ultimi mesi',
    'statsWillAppear': 'Le statistiche appariranno dopo le prime vendite',
    'mostSoldGiftCards': 'Gift Card più Vendute',
    'noGiftCardsSold': 'Nessuna gift card venduta',
    'revenueLastSixMonths': 'Fatturato ultimi 6 mesi',
    'totalTransactions': 'transazioni totali',
    'monthlyAverage': 'Media mensile',
    'salesPerMonth': 'Vendite per mese negli ultimi 6 mesi',
    'averageGiftCardValue': 'Valore medio gift card',
    'averageAmount': 'Importo medio per transazione',
    'showingTop5': 'Mostrando le top 5 gift card più vendute',
    'fullyUsed': 'Completamente utilizzata',
    'remaining': 'rimanente',
    'soldCount': 'vendute',
    'sold': 'vendite',
    'useGiftCard': 'Utilizza Gift Card',
    'settings': 'Impostazioni',
    'scanQROrEnterCode': 'Scansiona il QR code o inserisci manualmente il codice della gift card',
    'scanQR': 'Scansiona QR',
    'manualCode': 'Codice Manuale',
    'qrScanner': 'Scanner QR Code',
    'pointCamera': 'Inquadra il QR code della gift card',
    'startScanner': 'Avvia Scanner (Demo)',
    'giftCardCode': 'Codice Gift Card',
    'verify': 'Verifica',
    'verifying': 'Verifica...',
    'validGiftCard': 'Gift Card Valida',
    'customer': 'Cliente',
    'purchasedOn': 'Acquistata il',
    'amountToUse': 'Importo da utilizzare',
    'all': 'Tutto',
    'maximum': 'Massimo',
    'howToUse': 'Come utilizzare:',
    'step1': '• Inserisci il codice della gift card nel campo sopra',
    'step2': '• Clicca "Verifica" per controllare la validità',
    'step3': '• Se valida, clicca "Utilizza" per completare la transazione',
    'cancel': 'Annulla',
    'processing': 'Elaborazione...',
    'use': 'Utilizza',
    'enterAmount': 'Inserisci importo',
    'error': 'Errore',
    'errorVerifying': 'Errore durante la verifica del codice',
    'enterValidAmount': 'Inserisci un importo valido',
    'giftCardUsed': 'Gift Card Utilizzata',
    'usedAmount': 'Utilizzati',
    'fromGiftCard': 'dalla gift card',
    'errorUsingGiftCard': 'Errore durante l\'utilizzo della gift card',
    'giftCard.label': 'Gift Card',
    'insertAmount': 'Inserisci importo'
  },
  en: {
    // Header
    'header.searchPlaceholder': 'Search shops, categories...',
    'header.favorites': 'Favorites',
    'header.profile': 'Profile',
    'header.hello': 'Hello',
    'header.logout': 'Logout',
    'header.login': 'Login',
    'header.tagline': 'Local-Eyes',
    
    // Hero section
    'hero.title': 'See local, Live local',
    'hero.subtitle': 'The eyes of your digital community. Discover, support and share gift cards from merchants in your neighborhood. Together we make the local economy flourish.',
    'hero.stats.merchants': 'Local Merchants',
    'hero.stats.giftCards': 'Gift Cards Activated',
    'hero.stats.neighborhoods': 'Connected Neighborhoods',
    
    // Mission Banner
    'mission.title': 'Our mission',
    'mission.quote': 'We bring the gaze back to local. Every gift card is an investment in the future of your neighborhood.',
    'mission.button': 'Join the movement',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.all': 'All',
    'common.or': 'or',
    
    // Shop listing
    'shops.featuredTitle': 'The faces of your neighborhood',
    'shops.featuredDescription': 'Every purchase is a look of trust. Get to know the stories of the merchants that make your neighborhood unique.',
    'shops.shopsFound': 'shops found',
    'shops.loadMore': 'Load more shops',
    'shops.noResults': 'No shops found with selected filters',
    'shops.clearFilters': 'Clear filters',
    'shops.unableToLoad': 'Unable to load shops',
    'shops.discoverGiftCards': 'Discover Gift Cards',
    'shops.giftCards': 'gift cards',
    
    // View toggle
    'view.list': 'List',
    'view.map': 'Map',
    
    // CTA Section
    'cta.title': 'Do you have a shop?',
    'cta.description': 'Join Localize and start selling your gift cards online. It\'s simple, fast and free.',
    'cta.registerShop': 'Register your shop',
    
    // Gift cards
    'giftCard.useNow': 'Use now',
    'giftCard.expired': 'Expired',
    'giftCard.active': 'Active',
    'giftCard.qrCodeTitle': 'Gift Card QR Code',
    'giftCard.showToMerchant': 'Show this QR code to the merchant to use your gift card',
    'giftCard.code': 'Code',
    'giftCard.details': 'Details',
    'giftCard.value': 'Value',
    'giftCard.remaining': 'Remaining',
    'giftCard.expiresOn': 'Expires on',
    'giftCard.message': 'Message',
    'giftCard.purchasedOn': 'Purchased on',
    'giftCard.status.active': 'Active',
    'giftCard.status.used': 'Used',
    'giftCard.status.expired': 'Expired',
    'giftCard.status.cancelled': 'Cancelled',
    'giftCard.status.estinta': 'Depleted',
    'giftCard.status.scaduta': 'Expired',
    'giftCard.status.inactive': 'Inactive',
    
    // Profile
    'profile.title': 'My profile',
    'profile.giftCards': 'My Gift Cards',
    'profile.activeGiftCards': 'Active Gift Cards',
    'profile.inactiveGiftCards': 'Inactive Gift Cards',
    'profile.quickActions': 'Quick Actions',
    'profile.favoriteShops': 'Favorite Shops',
    'profile.settings': 'Settings',
    'profile.myLocations': 'My Locations',
    'profile.visit': 'Visit',
    'profile.noGiftCards': 'You haven\'t purchased any gift cards yet',
    'profile.exploreShops': 'Explore Shops',
    'profile.loadingGiftCards': 'Loading gift cards...',
    'profile.accessRequired': 'Access Required',
    'profile.loginToAccess': 'Please log in to access your profile',
    'profile.login': 'Login',
    'profile.backToHome': 'Back to Home',
    'profile.merchantDashboard': 'Merchant Dashboard',
    'profile.merchantDescription': 'Access your dashboard to manage gift cards and monitor sales',
    'profile.goToDashboard': 'Go to Dashboard',
    
    // Login Select
    'loginSelect.title': 'Choose your access type',
    'loginSelect.description': 'Select how you want to access Localize',
    'loginSelect.customer': 'Customer',
    'loginSelect.customerDescription': 'Log in to buy gift cards and discover shops in your neighborhood',
    'loginSelect.loginAsCustomer': 'Login as Customer',
    'loginSelect.merchant': 'Merchant',
    'loginSelect.merchantDescription': 'Manage your shop, gift cards and monitor sales',
    'loginSelect.loginAsMerchant': 'Login as Merchant',
    
    // Login
    'login.title': 'Localize',
    'login.description': 'Login or register to manage your gift cards',
    'login.tab.login': 'Login',
    'login.tab.signup': 'Sign Up',
    'login.email': 'Email',
    'login.emailPlaceholder': 'your-email@example.com',
    'login.password': 'Password',
    'login.passwordPlaceholder': '••••••••',
    'login.confirmPassword': 'Confirm Password',
    'login.fullName': 'Full Name',
    'login.namePlaceholder': 'Your name',
    'login.rememberMe': 'Remember me',
    'login.loginButton': 'Login',
    'login.signupButton': 'Sign Up',
    'login.loggingIn': 'Logging in...',
    'login.signingUp': 'Signing up...',
    'login.continueWithGoogle': 'Continue with Google',
    'login.loginSuccess': 'Login successful',
    'login.welcomeMessage': 'Welcome to Localize!',
    'login.loginError': 'Login error',
    'login.invalidCredentials': 'Invalid email or password',
    'login.signupSuccess': 'Registration completed',
    'login.signupWelcome': 'Welcome to Localize! Please log in to continue.',
    'login.signupError': 'Registration error',
    'login.signupGenericError': 'An error occurred during registration',
    'login.passwordMismatch': 'Passwords do not match',
    
    // 404
    'notFound.title': '404',
    'notFound.description': 'Oops! Page not found',
    'notFound.returnHome': 'Return to Home',
    
    // Shop Detail
    'shop.notFound': 'Shop not found',
    'shop.description': 'Description',
    'shop.contactInfo': 'Contact Information',
    'shop.openingHours': 'Opening Hours',
    'shop.schedule': 'Mon-Sat: 09:00 - 19:00',
    'shop.phone': 'Phone',
    'backToCatalog': 'Back to catalog',
    'backToHome': 'Back to Home',
    'reviews': 'reviews',
    'giftCard.available': 'Available Gift Cards',
    'giftCard.buy': 'Buy Gift Card',
    'giftCard.selectAmount': 'Select an amount',
    'giftCard.securePayment': 'Secure payment',
    'giftCard.instantDelivery': 'Instant delivery',
    
    // Categories  
    'categories.all': 'All',
    'categories.bar': 'Bars & Cafés',
    'categories.restaurant': 'Restaurants',
    'categories.bookstore': 'Bookstores',
    'categories.beauty': 'Beauty',
    'categories.clothing': 'Clothing',
    
    // Profile dropdown
    'profile.greeting': 'Hello',
    'profile.dashboard': 'Dashboard',
    'profile.logout': 'Sign out',
    'profile.defaultUser': 'user',
    
    // Shop cards  
    'shop.sampleDescription': 'Discover this fantastic local shop offering quality products and services in the heart of the neighborhood.',
    'merchant.verified': 'Verified Merchant',
    
    // Filters
    'filters.title': 'Filters',
    'filters.shopsTitle': 'Shop Filters',
    'filters.clearAll': 'Clear all', 
    'filters.category': 'Category',
    'filters.priceRange': 'Gift Card Price Range',
    'filters.minRating': 'Minimum rating',
    'filters.allRatings': 'All',
    'filters.maxDistance': 'Maximum distance',
    'filters.allDistances': 'All',

    // Dashboard translations
    'allShops': 'All shops',
    'selectedShop': 'Selected shop',
    'details': 'Details',
    'active': 'Active',
    'used': 'Used',
    'expired': 'Expired',
    'cancelled': 'Cancelled',

    // Merchant translations
    'merchant.login.title': 'Merchant Area',
    'merchant.login.description': 'Login or register to manage gift cards',
    'merchant.login.backHome': 'Back to home',
    'merchant.login.shopName': 'Shop name',
    'merchant.login.shopNamePlaceholder': 'Your shop name',
    'merchant.login.confirmPassword': 'Confirm Password',
    'merchant.login.registerButton': 'Register as Merchant',
    'merchant.login.customerAccountConnected': 'Customer account already connected',
    'merchant.login.mustLogoutCustomer': 'You must log out from the customer account to access as merchant.',
    'merchant.login.disconnect': 'Disconnect',
    'merchant.login.disconnected': 'Disconnected',
    'merchant.login.canLoginMerchant': 'Now you can login as merchant.',
    'merchant.login.loggingIn': 'Logging in...',
    'merchant.login.registrationInProgress': 'Registration in progress...',
    'merchant.login.registrationComplete': 'Registration completed',
    'merchant.login.registrationWelcome': 'Welcome! Please login to access the dashboard.',
    'merchant.login.registrationError': 'Registration error',
    'merchant.login.customerLogin': 'Are you a customer?',
    'merchant.login.loginAsCustomer': 'Login as customer',

    'merchant.shops.title': 'Your shops',
    'merchant.shops.description': 'Manage information and configurations of your shops',
    'merchant.shops.addShop': 'Add shop',
    'merchant.shops.backToDashboard': 'Back to Dashboard',
    'merchant.shops.modify': 'Edit',
    'merchant.shops.loadingError': 'Error loading shops',
    'merchant.shops.retry': 'Retry',
    'merchant.shops.noShops': 'No shops registered',
    'merchant.shops.registerFirst': 'Start by registering your first shop to sell gift cards online',
    'merchant.shops.registerFirstShop': 'Register first shop',
    'merchant.shops.shopUpdated': 'Shop updated',
    'merchant.shops.updatedSuccess': 'Changes have been saved successfully.',
    'merchant.shops.featureComingSoon': 'Feature coming soon',
    'merchant.shops.advancedSettings': 'Advanced settings will be available soon.',
    'merchant.shops.statusActive': 'Active',
    'merchant.shops.statusInactive': 'Inactive',
    'merchant.shops.statusPending': 'Under review',

    'merchant.settings.title': 'Settings',
    'merchant.settings.merchantSettings': 'Merchant Settings',
    'merchant.settings.manageShop': 'Manage your shop and gift card settings',
    'merchant.settings.shop': 'Shop',
    'merchant.settings.giftCards': 'Gift Cards',
    'merchant.settings.notifications': 'Notifications',
    'merchant.settings.security': 'Security',
    'merchant.settings.shopInfo': 'Shop Information',
    'merchant.settings.shopName': 'Shop Name',
    'merchant.settings.phone': 'Phone',
    'merchant.settings.description': 'Description',
    'merchant.settings.address': 'Address',
    'merchant.settings.website': 'Website',
    'merchant.settings.openingHours': 'Opening Hours',
    'merchant.settings.giftCardConfig': 'Gift Card Configuration',
    'merchant.settings.minAmount': 'Minimum Amount (€)',
    'merchant.settings.maxAmount': 'Maximum Amount (€)',
    'merchant.settings.defaultValidity': 'Default Validity (months)',
    'merchant.settings.defaultAmounts': 'Default Amounts (€)',
    'merchant.settings.customDesign': 'Custom Design',
    'merchant.settings.customDesignDesc': 'Enable custom design for gift cards',
    'merchant.settings.notificationPrefs': 'Notification Preferences',
    'merchant.settings.emailOrders': 'Email Order Notifications',
    'merchant.settings.emailOrdersDesc': 'Receive email for every new order',
    'merchant.settings.emailRedemptions': 'Email Usage Notifications',
    'merchant.settings.emailRedemptionsDesc': 'Receive email when a gift card is used',
    'merchant.settings.smsNotifications': 'SMS Notifications',
    'merchant.settings.smsDesc': 'Receive SMS for important events',
    'merchant.settings.weeklyReports': 'Weekly Reports',
    'merchant.settings.weeklyReportsDesc': 'Receive sales reports every week',
    'merchant.settings.monthlyReports': 'Monthly Reports',
    'merchant.settings.monthlyReportsDesc': 'Receive detailed reports every month',
    'merchant.settings.securitySettings': 'Security Settings',
    'merchant.settings.twoFactorAuth': 'Two-Factor Authentication',
    'merchant.settings.twoFactorDesc': 'Add an extra layer of security to your account',
    'merchant.settings.sessionTimeout': 'Session Timeout (minutes)',
    'merchant.settings.passwordExpiry': 'Password Expiry (days)',
    'merchant.settings.changePassword': 'Change Password',
    'merchant.settings.cancel': 'Cancel',
    'merchant.settings.save': 'Save Settings',
    'merchant.settings.saving': 'Saving...',
    'merchant.settings.saved': 'Settings Saved',
    'merchant.settings.savedDesc': 'Your settings have been updated successfully',
    'merchant.settings.error': 'Error',
    'merchant.settings.errorDesc': 'Error saving settings',
    
    // Merchant Dashboard
    'merchant.dashboard': 'Merchant Dashboard',
    'merchant.selectShop': 'Select shop',
    'merchant.allShops': 'All shops',
    'merchant.manageShops': 'Manage Shops',
    'merchant.logout': 'Logout',
    'merchant.loading': 'Loading...',
    'merchant.authenticationInProgress': 'Authentication verification in progress',
    'merchant.selectedShop': 'Selected Shop',
    'merchant.totalSales': 'Total Sales',
    'merchant.giftCardsSold': 'Gift Cards Sold',
    'merchant.pendingRedemptions': 'Pending',
    'merchant.totalCustomers': 'Total Customers',
    'merchant.pendingGiftCards': 'Pending gift cards',
    'merchant.newCustomers': 'new customers',
    'merchant.vsLastMonth': 'vs last month',
    'merchant.orders': 'Orders',
    'merchant.giftCards': 'Gift Cards',
    'merchant.analytics': 'Analytics',
    'merchant.recentOrders': 'Recent Orders',
    'merchant.export': 'Export',
    'merchant.noOrdersFound': 'No orders found',
    'merchant.tryChangeShop': 'Try changing shop or view all shops',
    'merchant.activeGiftCards': 'Active Gift Cards',
    'merchant.noActiveGiftCards': 'No active gift cards',
    'merchant.usedGiftCards': 'Used Gift Cards',
    'merchant.noUsedGiftCards': 'No used gift cards',
    'merchant.for': 'For:',
    'merchant.salesTrend': 'Sales Trend',
    'merchant.salesByMonth': 'Sales by Month',
    'merchant.giftCardSales': 'Gift Card Sales',
    'merchant.giftCardsSoldByMonth': 'Gift Cards Sold by Month',
    'merchant.noData': 'No data available',
    'merchant.sales': 'Sales',
    'merchant.giftCardsSoldCount': 'Gift Cards Sold',
    
    // Additional translations
    'giftCardStats': 'Gift Card Statistics',
    'remainingValue': 'Remaining Value',
    'usedValue': 'Used Value',
    'totalGiftCards': 'Total Gift Cards',
    'totalValue': 'Total Value',
    'noSalesLastMonths': 'No sales in recent months',
    'statsWillAppear': 'Statistics will appear after first sales',
    'mostSoldGiftCards': 'Best Selling Gift Cards',
    'noGiftCardsSold': 'No gift cards sold',
    'revenueLastSixMonths': 'Revenue Last 6 Months',
    'totalTransactions': 'total transactions',
    'monthlyAverage': 'Monthly Average',
    'salesPerMonth': 'Sales per month in last 6 months',
    'averageGiftCardValue': 'Average Gift Card Value',
    'averageAmount': 'Average amount per transaction',
    'showingTop5': 'Showing top 5 best selling gift cards',
    'fullyUsed': 'Fully Used',
    'remaining': 'remaining',
    'soldCount': 'sold',
    'sold': 'sales',
    
    // Additional translations needed
    'useGiftCard': 'Use Gift Card',
    'settings': 'Settings',
    
    // QR Redemption Modal
    'scanQROrEnterCode': 'Scan QR code or manually enter gift card code',
    'scanQR': 'Scan QR',
    'manualCode': 'Manual Code',
    'qrScanner': 'QR Code Scanner',
    'pointCamera': 'Point camera at gift card QR code',
    'startScanner': 'Start Scanner (Demo)',
    'giftCardCode': 'Gift Card Code',
    'verify': 'Verify',
    'verifying': 'Verifying...',
    'validGiftCard': 'Valid Gift Card',
    'customer': 'Customer',
    'purchasedOn': 'Purchased on',
    'amountToUse': 'Amount to use',
    'all': 'All',
    'maximum': 'Maximum',
    'howToUse': 'How to use:',
    'step1': '• Enter gift card code in the input above',
    'step2': '• Click "Verify" to check validity',
    'step3': '• If valid, click "Use" to complete transaction',
    'cancel': 'Cancel',
    'processing': 'Processing...',
    'use': 'Use',
    'enterAmount': 'Enter amount',
    'error': 'Error',
    'errorVerifying': 'Error verifying code',
    'enterValidAmount': 'Enter a valid amount',
    'giftCardUsed': 'Gift Card Used',
    'usedAmount': 'Used',
    'fromGiftCard': 'from gift card',
    'errorUsingGiftCard': 'Error using gift card',
    
    // More translations
    'giftCard.label': 'Gift Card',
    'insertAmount': 'Insert amount'
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'it';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    // First try to get the translation directly (flat structure)
    const translation = translations[language][key];
    if (translation) {
      return translation;
    }
    
    // Fallback: try nested structure
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      if (value && typeof value === 'object' && k in value) {
        value = value[k];
      } else {
        console.warn(`Translation key not found: ${key} for language: ${language}`);
        console.log('Available keys:', Object.keys(translations[language]).filter(k => k.startsWith(key.split('.')[0])));
        return key; // Return the key if path doesn't exist
      }
    }
    
    return typeof value === 'string' ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};