// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ueatznkuqvhnogkhovzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVlYXR6bmt1cXZobm9na2hvdnp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMTIwMjgsImV4cCI6MjA2ODg4ODAyOH0.Z33Yfhm5yUwBL3XacwUo8X9j_uIIOHBA6Fa-aU_jDEA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});